import json
import os
import boto3
from datetime import datetime, timedelta

cloudwatch = boto3.client("cloudwatch",  region_name=os.environ.get("AWS_REGION", "us-east-1"))
xray       = boto3.client("xray",        region_name=os.environ.get("AWS_REGION", "us-east-1"))
sns        = boto3.client("sns",         region_name=os.environ.get("AWS_REGION", "us-east-1"))
bedrock    = boto3.client("bedrock-runtime", region_name=os.environ.get("AWS_REGION", "us-east-1"))

SNS_TOPIC_ARN    = os.environ["SNS_TOPIC_ARN"]
BEDROCK_MODEL_ID = os.environ.get("BEDROCK_MODEL_ID", "anthropic.claude-3-sonnet-20240229-v1:0")

SYSTEM_PROMPT = """
You are an AWS Site Reliability Engineer responding to a CloudWatch alarm.
You receive alarm details and recent X-Ray trace summaries.
Your job is to generate a clear, actionable incident runbook.

Respond with ONLY a JSON object:
{
  "incident_title": "short title describing the issue",
  "severity": "critical|high|medium|low",
  "summary": "2-3 sentences explaining what is happening and why it matters",
  "root_cause_hypothesis": "most likely cause based on the traces and alarm data",
  "immediate_actions": [
    {"step": 1, "action": "what to do", "command": "aws cli or console command if applicable"}
  ],
  "investigation_steps": [
    {"step": 1, "description": "what to check", "command": "aws cli command"}
  ],
  "resolution_criteria": "how to know when the incident is resolved"
}
"""


def get_recent_traces(function_name: str) -> list:
    """Fetch recent X-Ray traces for the failing function."""
    end_time   = datetime.utcnow()
    start_time = end_time - timedelta(minutes=15)

    try:
        response = xray.get_trace_summaries(
            StartTime  = start_time,
            EndTime    = end_time,
            FilterExpression = f'service("{function_name}") AND error = true',
            SamplingStrategy = {"Name": "PartialScan"}
        )

        traces = []
        for trace in response.get("TraceSummaries", [])[:5]:
            traces.append({
                "trace_id":    trace.get("Id"),
                "duration":    trace.get("Duration"),
                "has_error":   trace.get("HasError"),
                "has_fault":   trace.get("HasFault"),
                "error_count": trace.get("ErrorRootCauses", []),
                "service_ids": [s.get("Name") for s in trace.get("ServiceIds", [])]
            })

        return traces

    except Exception as e:
        print(f"Error fetching X-Ray traces: {e}")
        return []


def get_alarm_details(alarm_name: str) -> dict:
    """Fetch CloudWatch alarm details."""
    try:
        response = cloudwatch.describe_alarms(AlarmNames=[alarm_name])
        alarms   = response.get("MetricAlarms", [])

        if alarms:
            alarm = alarms[0]
            return {
                "name":        alarm.get("AlarmName"),
                "description": alarm.get("AlarmDescription"),
                "state":       alarm.get("StateValue"),
                "reason":      alarm.get("StateReason"),
                "metric":      alarm.get("MetricName"),
                "namespace":   alarm.get("Namespace"),
                "threshold":   alarm.get("Threshold"),
                "dimensions":  {d["Name"]: d["Value"] for d in alarm.get("Dimensions", [])}
            }
    except Exception as e:
        print(f"Error fetching alarm details: {e}")

    return {}


def generate_runbook_with_bedrock(alarm: dict, traces: list) -> dict:
    """Call AWS Bedrock to generate an AI runbook."""
    user_message = f"""
A CloudWatch alarm has fired. Generate an incident runbook.

ALARM DETAILS:
{json.dumps(alarm, indent=2)}

RECENT X-RAY TRACES (errors only, last 15 minutes):
{json.dumps(traces, indent=2)}

Timestamp: {datetime.utcnow().isoformat()}
"""

    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens":        1024,
        "system":            SYSTEM_PROMPT,
        "messages": [
            {"role": "user", "content": user_message}
        ]
    })

    response = bedrock.invoke_model(
        modelId     = BEDROCK_MODEL_ID,
        body        = body,
        contentType = "application/json",
        accept      = "application/json"
    )

    response_body = json.loads(response["body"].read())
    raw           = response_body["content"][0]["text"].strip()

    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    return json.loads(raw.strip())


def send_runbook_email(runbook: dict, alarm_name: str):
    """Send the runbook via SNS email."""
    subject = f"[{runbook.get('severity', 'UNKNOWN').upper()}] {runbook.get('incident_title', alarm_name)}"

    body = f"""
INCIDENT RUNBOOK
Generated by AWS Observability Platform + Bedrock AI
{'='*60}

TITLE: {runbook.get('incident_title')}
SEVERITY: {runbook.get('severity', '').upper()}
TIME: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

SUMMARY:
{runbook.get('summary')}

ROOT CAUSE HYPOTHESIS:
{runbook.get('root_cause_hypothesis')}

IMMEDIATE ACTIONS:
{chr(10).join([f"{a['step']}. {a['action']}" + (f"\n   $ {a['command']}" if a.get('command') else '') for a in runbook.get('immediate_actions', [])])}

INVESTIGATION STEPS:
{chr(10).join([f"{s['step']}. {s['description']}" + (f"\n   $ {s['command']}" if s.get('command') else '') for s in runbook.get('investigation_steps', [])])}

RESOLUTION CRITERIA:
{runbook.get('resolution_criteria')}

{'='*60}
AWS Observability Platform | Powered by Amazon Bedrock
"""

    sns.publish(
        TopicArn = SNS_TOPIC_ARN,
        Subject  = subject[:100],
        Message  = body
    )

    print(f"Runbook sent via SNS: {subject}")


def lambda_handler(event, context):
    """
    Triggered by CloudWatch alarm.
    Reads alarm + X-Ray traces, calls Bedrock, sends runbook via SNS.
    """
    print(f"Runbook generator triggered: {json.dumps(event)}")

    # Extract alarm name from SNS message or direct invocation
    alarm_name = None
    if "Records" in event:
        message    = json.loads(event["Records"][0]["Sns"]["Message"])
        alarm_name = message.get("AlarmName")
    else:
        alarm_name = event.get("alarm_name", "high-error-rate-dev")

    print(f"Processing alarm: {alarm_name}")

    alarm  = get_alarm_details(alarm_name)
    traces = get_recent_traces("order-service")

    print(f"Fetched alarm details and {len(traces)} traces")

    runbook = generate_runbook_with_bedrock(alarm, traces)
    print(f"Generated runbook: {runbook.get('incident_title')}")

    send_runbook_email(runbook, alarm_name)

    return {
        "statusCode": 200,
        "runbook":    runbook
    }